import Superagent from 'superagent';
import Pagination from './Pagination';
let EventEmitter = require('events').EventEmitter;


const PhotoAPIUtils = {

    eventEmitter: EventEmitter.prototype,

    addRecieveListener: function(callback) {
        EventEmitter.prototype.on('recieve', callback);
    },
    removeRecieveListener: function(callback){
        EventEmitter.prototype.removeListener('recieve', callback);
    },

    getPhotos: function(limit, offset) {
        let raw;
/*
        raw = [
            {
                "id": "1",
                "contributionTime": "2016-04-14 18:33:49",
                "contributionName": "Утро в сосновом бору",
                "contributionDescription": "Ну краски там холст, типа круто",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d33.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "1",
                "participantTime": "2016-04-15 12:38:26",
                "idDeclarant": "1",
                "participantName": "Василий",
                "surname": "Шакула",
                "patronymic": "132132132132130231",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1900',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "2",
                "contributionTime": "2016-04-15 12:43:44",
                "contributionName": "Явление Христа народу",
                "contributionDescription": "Большое полотно, много времени и сил",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d34.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "2",
                "participantTime": "2016-04-15 12:45:00",
                "idDeclarant": "2",
                "participantName": "Михаил",
                "surname": "Шведов",
                "patronymic": "Иванович",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1912',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "3",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d35.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "3",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "3",
                "participantName": "Ефим",
                "surname": "Ююкин",
                "patronymic": "Андрианович",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1906',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "4",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d37.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "4",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "3",
                "participantName": "Пальмов",
                "surname": "Дмитрий",
                "patronymic": "Николаевич",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '5435',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "5",
                "contributionTime": "2016-04-15 12:43:44",
                "contributionName": "Явление Христа народу",
                "contributionDescription": "Большое полотно, много времени и сил",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d42.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "5",
                "participantTime": "2016-04-15 12:45:00",
                "idDeclarant": "5",
                "participantName": "Бондаренко",
                "surname": "Николай",
                "patronymic": "Иванович",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1234',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "6",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d43.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "6",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "3",
                "participantName": "Андреев",
                "surname": "Михаил",
                "patronymic": "",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1912',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "7",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d46.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "7",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "7",
                "participantName": "Кацоев",
                "surname": "Лев",
                "patronymic": "Сергеевич",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1910',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "8",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d47.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "8",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "8",
                "participantName": "Шопин",
                "surname": "Александр",
                "patronymic": "Романович",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1912',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "9",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d55.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "9",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "8",
                "participantName": "Золотаев",
                "surname": "Семен",
                "patronymic": "Васильевич",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1920',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "10",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d65.jpg',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "10",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "8",
                "participantName": "Зимин",
                "surname": "Михаил",
                "patronymic": "",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1920',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
            {
                "id": "11",
                "contributionTime": "2016-04-15 12:44:27",
                "contributionName": "Портрет неизвестной",
                "contributionDescription": "А она ниче так..",
                "storePath": 'null',
                "webPath": 'http://foto1945.mir24.tv/files/p1d93.png',
                "fileName": 'null',
                "contributionModeration": 'null',
                "contributionRejection": 'null',
                "category": 'null',
                "priority": 'null',
                "type": 'null',
                "fileSize": 'null',
                "idParticipant": "11",
                "participantTime": "2016-04-15 12:45:25",
                "idDeclarant": "8",
                "participantName": "Дубов",
                "surname": "Василий",
                "patronymic": "Алексеевич",
                "participantDescription": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sed elementum orci. Suspendisse vestibulum odio et purus pulvinar, non lacinia risus malesuada. Aenean fermentum, justo ac sagittis porta, libero ex blandit est, nec tincidunt magna ante non justo. Aliquam tristique nisl enim. Duis pulvinar blandit enim quis facilisis. In porttitor placerat bibendum. Fusce convallis mollis metus vel sed.',
                "year": '1920',
                "participantModeration": 'null',
                "participantRejection": 'null',
                "team": 'null',
            },
        ];
        this.eventEmitter.emit('recieve', raw, limit, offset, 80);
*/
        Superagent.get('/api/v1/contributionSigned/getList/'+limit+'/'+offset)
               .end(function(err, res) {
                if (res && res.body && !res.body.error) {
                    raw = res.body.data;
                    let total=res.body.meta.total;
                    PhotoAPIUtils.eventEmitter.emit('recieve', raw, limit, offset, total);
                } else if (res.body.error){
                    console.log(res.body.error['message']+' | '+res.body.error['legend']);
                } //TODO обработать err
            });
    },
    getDetailInfo: function(photo_id) {

        let info = {};/*
        info.photo = {
            "id": "1",
            "time": "2016-04-14 18:33:49",
            "idParticipant": "1",
            "name": "Утро в сосновом бору",
            "description": "Ну краски там холст, типа круто",
            "storePath": null,
            "webPath": 'http://foto1945.mir24.tv/files/p1d37.jpg',
            "fileName": null,
            "moderation": null,
            "rejection": null,
            "category": null,
            "priority": null,
            "type": null,
            "fileSize": null,
        };
        info.participant= {
            "id": "1",
            "time": "2016-04-15 12:38:26",
            "idDeclarant": "1",
            "name": "Дмитрий",
            "surname": "Пальмов",
            "patronymic": "Олегович",
            "description": 'Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).',
            "year": '1990',
            "moderation": null,
            "rejection": null,
            "team": null,
        };*/

        Superagent.get('/api/v1/contribution/get/'+photo_id)
            .end(function(err, res) {
                if (res && res.body) {
                    info.photo = res.body;
                    Superagent.get('/api/v1/contribution/get/'+info.photo.idParticipant)
                        .end(function(err, res) {
                            if (res && res.body) {
                                info.participant = res.body;
                            } //TODO обработать err
                        });
                } //TODO обработать err
            });
        return info;
    },
};

module.exports = PhotoAPIUtils;